language: node_js
node_js:
- stable
sudo: false
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
after_script:
- npm run coveralls
deploy:
  provider: heroku
  api_key:
    secure: iEYTg18UvY6snKkKUmLNYhJ6fiznr7iCR32T4f4oiJa8+67NaN0Lz2w0MTwWIpPr9MjuctNb6syH24uXx3NSOK4dOuwKjZrgtX8p58Tx4fjzznSl1DAk8p2+XtkkJmwU8y+KaqIrENO7m9Hk+04MsbUwllDdmShTHq2FRQY5wFxd0nKv8bE6AzZvAi7Ul1HsiHkEsygnVELYYZ2CiAiUFzKRrjgpn7tGqRYHREzeoKANJPpb/8WvBVbyOG73qqKU0InCyupWtQSTKFKtyho5MbrWpMb4dqzS9J35aLMo/5QnKZ0u+QKSCCIbIzssdgLabVH5p9OEhXbef2xTW6JEAccltG/d8ojELjirBn78GFWQ73rviB4Z4AYAx2T62uaHiNe9OE2bC4MziIELdsmwjsQc/qh62uSjSfhKQS3fLLh7oPQrA/HI1oFOcSHxWCDva8+C/I9W6JN55oyy4aScg5y2094vwaVfMFGbAsVPYGftnBnS07mtGonwpgybyBAeDmWlDOiOrB9Lm8RoqI4mmWugNdtJC+FFv7kwRaxP+Kbisn8aaluNtiLEeM0R51UxLqVVY3d2DWl8Z92+5zQtrdcpf77wAmaUHW1d+wtC8UGGuA9bj6mF53cBaJCIyPtc1gPzka7pJ8co4E8slcayUbrcxZ8cG0097dllT6rH0po=
  app: stormy-lowlands-15129
  on:
    repo: asasmith/whitebox-challenge-server
