language: node_js

node_js:
  - 11.3

sudo: false

cache:
  directories:
  - node_modules

before_install:
- npm update

install:
- npm install

script:
- jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage